spring:
  application:
    name: nfg_gunny_playerhub
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}
  messages:
    basename: ValidationMessages


logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
    security: TRACE